# Generated by Django 3.0.3 on 2020-02-19 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='game',
        ),
    ]
