# Generated by Django 3.0.3 on 2020-02-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_agent_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.AddField(
            model_name='game',
            name='agent1',
            field=models.CharField(default='agent', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='agent2',
            field=models.CharField(default='agent', max_length=100),
        ),
    ]
