# Generated by Django 3.0.3 on 2020-02-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_agent_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameID',
            field=models.CharField(default='blackjack', max_length=100),
        ),
    ]
