# Generated by Django 3.0.3 on 2020-02-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0008_auto_20200221_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='rank',
        ),
        migrations.AddField(
            model_name='agent',
            name='agentName',
            field=models.CharField(default='DQN', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agentID',
            field=models.CharField(default='agent007', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='gamesPlayed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='agent',
            name='gamesWon',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='agent',
            name='opponent',
            field=models.CharField(default='DQN', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='totalGamesPlayed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='agent',
            name='winRate',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameID',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='replayID',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='replayLink',
            field=models.CharField(default='replay00001', max_length=100),
        ),
    ]
