# Generated by Django 3.0.3 on 2020-02-25 01:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0010_auto_20200224_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameName',
            field=models.CharField(default="Leduc Hold'em", max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agentID',
            field=models.CharField(default=uuid.UUID('63db4377-14d9-495c-be7f-4f202226277e'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameID',
            field=models.CharField(default=uuid.UUID('fcc0a8ae-ade7-4abe-9e70-2cc64bd4230b'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='replayID',
            field=models.CharField(default=uuid.UUID('44ec8c34-9cf5-4cc9-8779-51baf936c7d2'), max_length=100, unique=True),
        ),
    ]
