# Generated by Django 3.1.4 on 2020-12-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('index', models.CharField(max_length=100)),
                ('agent0', models.CharField(max_length=100)),
                ('agent1', models.CharField(max_length=100)),
                ('win', models.BooleanField()),
                ('payoff', models.FloatField()),
                ('replay', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agent0', models.CharField(max_length=100)),
                ('agent1', models.CharField(max_length=100)),
                ('payoff', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadedAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('game', models.CharField(max_length=100)),
                ('f', models.FileField(upload_to='uploaded_agents')),
            ],
        ),
    ]
